export const SDG_GOALS = [
  { id: 1, label: "No Poverty" },
  { id: 2, label: "Zero Hunger" },
  { id: 3, label: "Good Health and Well-being" },
  { id: 4, label: "Quality Education" },
  { id: 5, label: "Gender Equality" },
  { id: 6, label: "Clean Water and Sanitation" },
  { id: 7, label: "Affordable and Clean Energy" },
  { id: 8, label: "Decent Work and Economic Growth" },
  { id: 9, label: "Industry, Innovation and Infrastructure" },
  { id: 10, label: "Reduced Inequalities" },
  { id: 11, label: "Sustainable Cities and Communities" },
  { id: 12, label: "Responsible Consumption and Production" },
  { id: 13, label: "Climate Action" },
  { id: 14, label: "Life Below Water" },
  { id: 15, label: "Life on Land" },
  { id: 16, label: "Peace, Justice and Strong Institutions" },
  { id: 17, label: "Partnerships for the Goals" },
];
